// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"seal/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/genPVC",
				Handler: GenPVCHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/genCVC",
				Handler: GenCVCHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/approval",
				Handler: ApprovlHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/revork",
				Handler: RevorkHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addsign",
				Handler: AddSignHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/querysign",
				Handler: QuerySignHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/downloadcid",
				Handler: DownloadCIDHandler(serverCtx),
			},
		},
	)
}
