// Code generated by goctl. DO NOT EDIT.
package types

type PVCReq struct {
	PPriKeyPath string `json:"pPriKeyPath"`
	Name        string `json:"name"`
	IdNumber    string `json:"idNumber"`
}

type PVCResp struct {
	TransHash string `json:"transHash"`
	BlockHash string `json:"blockHash"`
	Identity  string `json:"identity"`
	PVCID     string `json:"PVCID"`
}

type CVCReq struct {
	LegalDid    string `json:"legalDid"`
	Name        string `json:"name"`
	CreditCode  string `json:"creditCode"`
	LegalName   string `json:"legalName"`
	CompanyType int    `json:"companyType"`
}

type CVCResp struct {
	TransHash   string `json:"transHash"`
	BlockHash   string `json:"blockHash"`
	Identity    string `json:"identity"`
	SealAddress string `json:"sealAddress"`
	CVCID       string `json:"CVCID"`
}

type ApprovalReq struct {
	SealAddress string `json:"sealAddress"`
	TargetDid   string `json:"targetDid"`
	AuthDid     string `json:"authDid"`
	CPriKeyPath string `json:"cPriKeyPath"`
}

type ApprovalResp struct {
	TransHash string `json:"transHash"`
	BlockHash string `json:"blockHash"`
	Res       string `json:"res"`
}

type RevokeReq struct {
	SealAddress string `json:"sealAddress"`
	TargetDid   string `json:"targetDid"`
	AuthDid     string `json:"authDid"`
	CPriKeyPath string `json:"cPriKeyPath"`
}

type RevokeResp struct {
	TransHash string `json:"transHash"`
	BlockHash string `json:"blockHash"`
	Res       string `json:"res"`
}

type AddSignReq struct {
	LegalDid         string            `json:"legalDid"`
	CreditCode       string            `json:"creditCode"`
	CVCID            string            `json:"CVCID"`
	CompanySealClaim map[string]string `json:"cmpanySealClaim"`
	NestCID          string            `json:"nestCID"`
	ContrachHash     string            `json:"contractHash"`
	SealType         uint8             `json:"sealType"`
}

type AddSignResp struct {
	TransHash    string `json:"transHash"`
	BlockHash    string `json:"blockHash"`
	ContractHash string `json:"contractHash"`
	SignHash     string `json:"signHash"`
	SealAddress  string `json:"sealAddress"`
	SealType     uint8  `json:"sealType"`
	SignAddress  string `json:"signAddress"`
	CID          string `json:"CID"`
}

type QuerySignReq struct {
	ContractHash string `json:"contractHash"`
	SignHash     string `json:"signHash"`
	SealAddress  string `json:"sealAddress"`
	SealType     uint8  `json:"sealType"`
	SignAddress  string `json:"signAddress"`
}

type QuerySignResp struct {
	CID         string `json:"cid"`
	SignHash    string `json:"signHash"`
	SealAddress string `json:"sealAddress"`
	SealType    uint8  `json:"sealType"`
	SignAddress string `json:"signAddress"`
	SignTime    string `json:"signTime"`
}

type DownloadCidReq struct {
	CID  string `json:"cid"`
	Path string `json:"path"`
}

type DownloadCidResp struct {
	Res string `json:"res"`
}
